name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Use official docker image
          use_prebuilt_image: yes

          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: RivenNero
          template: classic
          base: header, activity, community, repositories
          config_padding: 100%, 10%
          config_timezone: Asia/Shanghai
          plugin_introduction: yes
          plugin_introduction_title: yes
